version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    volumes:
      - ./server:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.26
    container_name: mysql
    command: --init-file /docker-entrypoint-initdb.d/setup.sql
    volumes:
      - ./server/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      MYSQL_USER: ids_project_2024
      MYSQL_ROOT_PASSWORD: ids_project_2024
      MYSQL_PASSWORD: ids_project_2024
      MYSQL_DATABASE: Articles
    ports:
      - "3307:3306"
    expose:
      - 3306
