services:
  client:
    image: 'nginx:alpine'
    ports:
      - '80:80'
    expose:
      - 80
    depends_on:
      - server
    volumes:
      - './client/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './client/public:/usr/share/nginx/html/'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '1234:1234'
    expose:
      - 1234
    volumes:
      - './server:/app'
    depends_on:
      db:
        condition: service_healthy
  db:
    image: 'mysql:5.7.26'
    command: >-
      --init-file /docker-entrypoint-initdb.d/setup.sql
      --explicit_defaults_for_timestamp=1
      --default-authentication-plugin=mysql_native_password
    volumes:
      - './server/setup.sql:/docker-entrypoint-initdb.d/setup.sql'
    environment:
      MYSQL_USER: ids_project_2024
      MYSQL_ROOT_PASSWORD: ids_project_2024
      MYSQL_PASSWORD: ids_project_2024
      MYSQL_DATABASE: Articles
    ports:
      - '3307:3306'
    expose:
      - 3306
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - status
        - '-h'
        - localhost
        - '-u'
        - ids_project_2024
        - '-pids_project_2024'
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
  zeek:
    image: 'zeek/zeek:lts'
    tty: true
    command:
      - /usr/local/zeek/bin/zeek
      - '-i'
      - any
      - '-C'
      - /usr/share/alerts.zeek
    network_mode: host
    volumes:
      - './docs/zeek/alerts.zeek:/usr/share/alerts.zeek'
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - server
      - client
