services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
    volumes:
      - ./client:/usr/share/nginx/html/

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    volumes:
      - ./server:/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7.26
    command: --init-file /docker-entrypoint-initdb.d/setup.sql --explicit_defaults_for_timestamp=1 --default-authentication-plugin=mysql_native_password
    volumes:
      - ./server/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      MYSQL_USER: ids_project_2024
      MYSQL_ROOT_PASSWORD: ids_project_2024
      MYSQL_PASSWORD: ids_project_2024
      MYSQL_DATABASE: Articles
    ports:
      - "3307:3306"
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pids_project_2024"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
